version: '3.8'
services:

  postgres_service:
    container_name: postgres_service
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB_NAME}
      PGDATA: /data/postgres_service
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${SQL_USER} -d ${SQL_DB_NAME}'"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  muzikaloid-api:
    container_name: muzikaloid_api
    build: ./muzikaloid_backend
    ports:
      - 3000:3000
    volumes:
      - ./muzikaloid_backend:/usr/src
      - "/usr/src/node_modules/"

    depends_on:
      postgres_service: 
        condition: service_healthy
